#!/bin/sh
#
#==>  WAM post-processing pgrid
#
#PBS -o /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/pgrid.log
#PBS -e /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/pgrid.log
#PBS -N  pgrid
# Account to run job (change the account name: See Accounting above)
#PBS -A nn2857k
#PBS -l select=1:ncpus=1
#PBS -l walltime=10:00:00
#

module load intelcomp/13.0.1  mpt/2.05  netcdf/4.1.3

WAMDIR=/home/metno/carrasco/MYWAVE_WAM/WAM10
WORK=/work/carrasco/MyWaveWAM/WAM10

cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Grid_User .
cp ${WAMDIR}/abs/pgrid pgrid.exe
#
./pgrid.exe
mv Grid_Prot ${WAMDIR}/dayfiles/pgrid_prot_c
#rm Grid_User pgrid.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
