#!/bin/bash
#
#==>  WAM post-processing prad
#
#PBS -o /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/prad.log
#PBS -e /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/prad.log
#PBS -N  prad
# Account to run job (change the account name: See Accounting above)
#PBS -A nn2857k
#PBS -l select=1:ncpus=1
#PBS -l walltime=15:00:00
#

module load intelcomp/13.0.1  mpt/2.06

WAMDIR=/home/metno/carrasco/MYWAVE_WAM/WAM10
WORK=/work/carrasco/MyWaveWAM/WAM10

cd ${WORK}/tempsg
#
cp ${WAMDIR}/const/Radiation_User .
cp ${WAMDIR}/abs/prad prad.exe
#
./prad.exe
mv Radiation_Prot ${WAMDIR}/dayfiles/prad_prot_c
rm Radiation_User prad.exe
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PGRID.
# ===================================================================
#
