#!/bin/sh
#
#==>  WAM post-processing ptime
#PBS -o /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/jptime.log
#PBS -e /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/jptime.log
#PBS -N  ptime
# Account to run job (change the account name: See Accounting above)
#PBS -A nn2857k
#PBS -l select=1:ncpus=1:mem=400mb
#PBS -l walltime=15:00:00
#

module load intelcomp/13.0.1  mpt/2.05  netcdf/4.1.3

WAMDIR=/home/metno/carrasco/MYWAVE_WAM/WAM10
WORK=/work/carrasco/MyWaveWAM/WAM10

cd ${WORK}/tempsg
#cp ${WAMDIR}/const/Time_User_nml Time_User
cp ${WAMDIR}/const/Time_User .
cp ${WAMDIR}/abs/ptime ptime.exe
#
./ptime.exe
mv Time_Prot ${WAMDIR}/dayfiles/ptime_prot_c
rm Time_User ptime.exe 
#
# ===================================================================
#  GRID FILES HAVE BEEN CREATED AND SAVED.
#  END OF JOB PTIME.
# ===================================================================
#
