#!/bin/sh
#PBS -o /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/wam.log
#PBS -e /home/metno/carrasco/MYWAVE_WAM/WAM10/jobs/wam.log
#PBS -N wam
# Account to run job (change the account name: See Accounting above)
#PBS -A nn2857k
#PBS -l select=2:ncpus=32:mpiprocs=16:mem=29000mb
#PBS -l walltime=24:00:00
#-----------------------------------------------
#-----------------------------------------------
#

module load intelcomp/13.0.1  netcdf/4.1.3

export MPI_STATS=1
export MPI_BUFS_PER_PROC=256
export MPI_BUFS_PER_HOST=1024

WAMDIR=/home/metno/carrasco/MYWAVE_WAM/WAM10
WORK=/work/carrasco/MyWaveWAM/WAM10

t=${WORK}/ready
if [ ! -d $t ]; then mkdir -p $t; fi

cd ${WORK}/tempsg
cp ${WAMDIR}/const/WAM_User .
cp ${WAMDIR}/const/ICE_INPUT.DAT .
#cp ${WAMDIR}/const/CURRCAT.DAT .
#cp ${WAMDIR}/const/OBS* .
cp ${WORK}/work/Grid_info*  .
cp ${WAMDIR}/const/WIND_INPUT.DAT .

cp ${WAMDIR}/abs/wam wam.exe


mpiexec_mpt  -np 32 wam.exe

#
cp logfile.0 ${WAMDIR}/dayfiles/wam_prot_c
mv BLS* MAP* OUT* RAD* C* ..
#rm wam.exe WAM_User WAM_Prot w2* log* Grid_info
#
exit 0
