#!/bin/sh
set -ex
. ${0%/*}/.dirset
SCRDIR=${PRODADMDIR}/mk
OBJDIR=${PRODADMDIR}/obj
EXECDIR=${PRODADMDIR}/abs
cp $SCRDIR/pnetcdf_spec.mk $OBJDIR
cd $OBJDIR
make -f pnetcdf_spec.mk pnetcdf_spec
mv pnetcdf_spec $EXECDIR
rm -f pnetcdf_spec.mk
