#!/bin/bash
#PBS -o wam.log
#PBS -e wam.err
#PBS -N wam
# Account to run job (change the account name: See Accounting above)
#PBS -A nn2857k
#PBS -l select=2:ncpus=32:mpiprocs=16:mem=29000mb
#PBS -l walltime=00:30:00
#-----------------------------------------------
#-----------------------------------------------
#

#module load intelcomp/13.0.1  netcdf/4.1.3

#export MPI_STATS=1
#export MPI_BUFS_PER_PROC=256
#export MPI_BUFS_PER_HOST=1024
#export PATH=/disk1/local/openmpi_gfortran/bin:$PATH
which mpirun

WAMDIR=..
WORK=..

t=${WORK}/ready
if [ ! -d $t ]; then mkdir -p $t; fi

cd ${WORK}/tempsg
cp ${WAMDIR}/const/WAM_User .
cp ${WORK}/work/Grid_info*  .
cp ${WAMDIR}/const/WIND_INPUT.DAT .
ln -s WIND_INPUT.DAT ICE_INPUT.DAT

cp ${WAMDIR}/abs/wam wam.exe


#mpiexec_mpt  -np 4 wam.exe
mpirun -np 1 wam.exe

#
cp logfile.0 ${WAMDIR}/dayfiles/wam_prot_c
mv BLS* MAP* OUT* RAD* C* ..
#rm wam.exe WAM_User WAM_Prot w2* log* Grid_info
#
exit 0
